### ISSUE TITLE
Branch redmine2.x not exists

### ISSUE THREAD

**Issue by pousterlus** [Enkil/redmine_reminder#1]
Hi,

In the installation notes, there's a mention to a "redmine2.x" checkout for redmine 2.x and higher compatibility.

But I can't see it on git... ?
## 

Léo.

**Comment by Enkil** [comment]
Hi,
you can ignore it and installation will be correctly

**Comment by pousterlus** [comment]
OK. Then why not remove that mention, and also add to run "bundle install" after the git thing, in order to avoid the :
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
Could not find gem 'factory_girl_rails (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.

? :)

Thanks,

## 

Léo.
