### ISSUE TITLE
Add links to issue page in email

### ISSUE THREAD

**Issue by stefandoorn** [Enkil/redmine_reminder#15]
The numbers in the e-mail could be made clickable to the issue detail page.

**Comment by DarkSideGeek** [comment]
Unless I am misunderstanding your suggestion -- or unless it was a late-addition feature -- they already are. Each line in the email links to $redmine/issues/###.

**Comment by stefandoorn** [comment]
I actually have no clue anymore after 2 years ;) I'm not using Redmine anymore so also can't really check it.
