### ISSUE TITLE
Support for redmine 3.x?

### ISSUE THREAD

**Issue by ilovetacos** [Enkil/redmine_reminder#21]
Hi,
i was wondering if you are planning to release a version for redmine v3.x?
Thank you very much!

**Comment by f0y** [comment]
No.

On Wed, Aug 5, 2015 at 11:47 AM, HannaH notifications@github.com wrote:

> Hi,
> i was wondering if you are planning to release a version for redmine v3.x?
> Thank you very much!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Enkil/redmine_reminder/issues/21.

## 

Best Wishes,
Oleg Kandaurov
