### ISSUE TITLE
config page missing 404

### ISSUE THREAD

**Issue by stf675** [Enkil/redmine_reminder#6]
Plugin installed.

when you click "configure" on Admin-Plugin page you end up with 404 error

it is looking for /plugin/due_date_reminder  folder which does not exist as installation go to /plugins/redmine_reminder

how to fix?

thanks

**Comment by Enkil** [comment]
try to rename folder to ./public_html/due_date_reminder

**Comment by stf675** [comment]
Small typo in my post:

it is looking for /redmine/settings/plugin/due_date_reminder

not sure what folder to rename, renaming  /plugins/redmine_reminder into /plugins/due_date_reminder does not help.

(unless I am renaming wrong folder)

**Comment by Enkil** [comment]
correct folder is
path_to_redmine/plugins/due_date_reminder

for example on my gentoo installation (nginx+unicorn+rvm)
/home/redmine2/public_html/redmine-law/plugins/due_date_reminder

**Comment by stf675** [comment]
renamed
ran "bundle exec rake redmine:plugins:migrate RAILS_ENV=production"
restarted services
works now.

Thanks
